export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADJUST_QTY = "ADJUST_QTY"
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const FETCH_PRODUCTS_SUCCESS= "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR"

